### ISSUE TITLE
Extension works only on first page of favourite blogs

### ISSUE THREAD

**Issue by jaglikemakkar** [cs-mshah/codeforces-customizer#3]
Hi, the extension works only for the URL: `https://codeforces.com/favourite/blogEntries/`. 

You can make the following change in `manifest.json.content_scripts.matches` to allow it to work for all pages:
Before: `"https://*.codeforces.com/favourite/blogEntries/*"`
After: `"https://*.codeforces.com/favourite/blogEntries*"`

**Comment by cs-mshah** [comment]
Thanks. Fixed.
